# Generated by Django 3.0.6 on 2020-05-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='withoutMigrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data3', models.CharField(max_length=400)),
                ('data4', models.CharField(max_length=500)),
            ],
        ),
    ]
