# Generated by Django 3.0.6 on 2020-05-10 22:12

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_withoutmigrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=myapp.models.upload_path)),
            ],
        ),
    ]
